# Generated by Django 5.1.3 on 2025-09-16 14:15

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Returned', 'Returned'), ('Failed Delivery', 'Failed Delivery')], default='Pending', max_length=50)),
                ('current_location_country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_contact_number', models.CharField(max_length=15)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_address', models.TextField()),
                ('receiver_country', django_countries.fields.CountryField(max_length=2)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_contact_number', models.CharField(max_length=15)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_address', models.TextField()),
                ('sender_country', django_countries.fields.CountryField(max_length=2)),
                ('item_description', models.TextField()),
                ('number_of_items', models.PositiveIntegerField(default=1)),
                ('parcel_colour', models.CharField(max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='Domestic', max_length=50)),
                ('destination_country', django_countries.fields.CountryField(max_length=2)),
                ('date_sent', models.DateField()),
                ('estimated_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_location_city', to='cities_light.city')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_city', to='cities_light.city')),
                ('receiver_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_city', to='cities_light.city')),
                ('sender_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_city', to='cities_light.city')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourierTrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Returned', 'Returned'), ('Failed Delivery', 'Failed Delivery')], max_length=50)),
                ('location_country', django_countries.fields.CountryField(max_length=2)),
                ('description', models.TextField(blank=True, help_text="Optional details (e.g. 'Departed Paris Airport' or 'Arrived at Lagos facility')")),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='accounts.courier')),
                ('location_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
