# Generated by Django 5.1.3 on 2025-09-16 14:24

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courier_couriertrackinghistory'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='current_location_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='current_location_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location_city', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='destination_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='destination_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='receiver_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='receiver_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_city', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='sender_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sender_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_city', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='couriertrackinghistory',
            name='location_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='location_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
