# Generated by Django 5.1.3 on 2025-09-16 14:48

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_courier_current_location_city_and_more'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='current_location_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_location_country', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_country', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='receiver_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_country', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='sender_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_country', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='couriertrackinghistory',
            name='location_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='location_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_location_city', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='couriertrackinghistory',
            name='location_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_location_country', to='cities_light.country'),
        ),
    ]
