# Generated by Django 5.1.3 on 2025-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_courier_current_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='scac',
            field=models.CharField(blank=True, default='N/A', help_text='Standard Carrier Alpha Code (SCAC)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='seal_number',
            field=models.CharField(default='9977', help_text='Seal Number', max_length=50),
        ),
        migrations.AddField(
            model_name='courier',
            name='trailer_number',
            field=models.CharField(default='332764', help_text='Trailer Number', max_length=50),
        ),
    ]
