"""
Django settings for net_courier project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ



from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pt*973+w2)4(l&j@z09dqlf#)z4-4%q(@r!uk$)+tqm7qvp&&9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://netexpressc.com"]
ALLOWED_HOSTS = ["netexpressc.com"]


# # Application definition
AUTH_USER_MODEL = 'accounts.Account'
# LOGIN_URL = '/Accounts/login/'


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms", 
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django_extensions",
    'import_export',
    'accounts',
    'django_countries',
    'cities_light',
    "smart_selects",
    "anymail",
    "django.contrib.sitemaps",
    "django.contrib.sites",
]

SITE_ID = 1



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'net_courier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'net_courier.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'



# if DEBUG:
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# else:
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# DEFAULT_FROM_EMAIL = 'info@net.com'


# EMAIL_BACKEND      = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST         = 'smtp.zoho.com'       # or smtp.zoho.com
# EMAIL_PORT         = 465
# EMAIL_USE_TLS      = False
# EMAIL_USE_SSL      = True
# EMAIL_HOST_USER    = env('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD= env('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
DEFAULT_FROM_EMAIL = "info@netexpressc.com"   # your verified sender email

ANYMAIL = {
    "RESEND_API_KEY": env("RESEND_API_KEY"),  # put your Resend API key in .env
}







UNFOLD = {
    "SITE_HEADER": "Net Express Courier",
    "SITE_TITLE": "Net Express Admin",
    "SITE_SUBHEADER": "Manage courier operations",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("assets/img/logo_dark.png"),
        "dark": lambda request: static("assets/img/logo_light.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("assets/img/logo_dark.png"),
        "dark": lambda request: static("assets/img/logo_light.png"),
    },
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": True,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:accounts_account_changelist"),
                "description": _("Manage registered users."),
            },
            {
                "title": _("Couriers"),
                "icon": "local_shipping",
                "link": reverse_lazy("admin:accounts_courier_changelist"),
                "description": _("Manage and track courier packages."),
            },
            {
                "title": _("Tracking History"),
                "icon": "history",
                "link": reverse_lazy("admin:accounts_couriertrackinghistory_changelist"),
                "description": _("View timeline of courier tracking updates."),
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Core"),
                "icon": "dashboard",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_account_changelist"),
                    },
                ],
            },
            {
                "title": _("Courier Management"),
                "icon": "local_shipping",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Couriers"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:accounts_courier_changelist"),
                    },
                    {
                        "title": _("Tracking History"),
                        "icon": "history",
                        "link": reverse_lazy("admin:accounts_couriertrackinghistory_changelist"),
                    },
                ],
            },
        ],
    },
}
